//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaypalIntegration.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDetail
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> Country { get; set; }
        public string Street { get; set; }
        public string LandMark { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
    }
}
